export const techStackLogos = [
  { imgSrc: "/logos/antd.png", alt: "Ant Design" },
  { imgSrc: "/logos/canva.png", alt: "Canva" },
  { imgSrc: "/logos/css3.png", alt: "CSS3" },
  { imgSrc: "/logos/figma.png", alt: "Figma" },
  { imgSrc: "/logos/github.png", alt: "GitHub" },
  { imgSrc: "/logos/git.png", alt: "Git" },
  { imgSrc: "/logos/html5.png", alt: "HTML5" },
  { imgSrc: "/logos/jest.png", alt: "Jest" },
  { imgSrc: "/logos/js.png", alt: "JavaScript" },
  { imgSrc: "/logos/mysql.png", alt: "MySQL" },
  { imgSrc: "/logos/nextjs2.png", alt: "Next.js" },
  { imgSrc: "/logos/nodejs.png", alt: "Node.js" },
  { imgSrc: "/logos/npm.png", alt: "npm" },
  { imgSrc: "/logos/postman.png", alt: "Postman" },
  { imgSrc: "/logos/python.png", alt: "Python" },
  { imgSrc: "/logos/reactjs.png", alt: "React.js" },
  { imgSrc: "/logos/sass.png", alt: "Sass" },
  { imgSrc: "/logos/shadcnui.png", alt: "shadcn/ui" },
  { imgSrc: "/logos/swagger.png", alt: "Swagger" },
  { imgSrc: "/logos/tailwindcss.png", alt: "Tailwind CSS" },
  { imgSrc: "/logos/typescript.png", alt: "TypeScript" },
];
